title: eBox-官网 | 简单、快速的开发平台供应商
subtitle: "eBox是一个快速、高效、跨平台的嵌入式软件解决方案."
description: "eBox是一个快速、高效、跨平台的嵌入式软件解决方案"
author: TongQiang Shen
language: en
timezone: UTC
url: https://eboxmake.com
root: /
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
highlight:
  enable: true
  line_number: false
per_page: 0

theme: navy
deploy:
  type: git
  repo: git@github.com:eboxmaker/ebox_stm32f1xx.github.io.git

disqus_shortname: hexojs
google_analytics: UA-4910098-10
fb_admins: 100000247608790
algolia:
  en:
    api_key: c3d5d4c995b5e0c2ffb5623900279a66
    index_name: hexo
  zh-tw:
    api_key: c83d2ec3440f40aec6d0e695ecec7ef3
    index_name: hexo_zh-tw
  zh-cn:
    api_key: cdea7d4e47d84f6145b77e7f68689f35
    index_name: hexo_zh-cn
twitter: eboxmaker
github: eboxmaker
